
const SELECT_INVOICE = 'SELECT_INVOICE';
const FETCH_INVOICE = 'FETCH_INVOICE';
const OPEN_DIALOG = 'OPEN_DIALOG'
const CLOSE_DIALOG = 'CLOSE_DIALOG'
export { SELECT_INVOICE, FETCH_INVOICE, OPEN_DIALOG, CLOSE_DIALOG };